version: '3.8'
services:
  acme:
    container_name: acme
    # Image for acme.sh
    image: docker.io/neilpang/acme.sh:3.0.6
    command: /bin/sh -c "sleep 3600"
    ports:
      - target: 80
        protocol: tcp

  vault-server:
    container_name: vault-server
    image: docker.io/hashicorp/vault:1.14.1
    command: /bin/sh -c "vault server -config=/vault/config -dev-root-token-id=root -dev-listen-address=0.0.0.0:8200 -dev-tls"
    environment:
      - VAULT_ADDR=https://127.0.0.1:8200      # cli config
      - VAULT_TOKEN=root                      # cli config
    ports:
      - target: 8200
        published: 8200
        protocol: tcp
